### PR TITLE
fix(skeleton): fix readonly environment files

### LINKED ISSUE #1031: Readonly attribute on environment scipt file
* **Library Version:**
aurelia-cli v1.0.0-beta.12

* **Operating System:**
Windows 10

* **Node Version:**
10.15.0

* **NPM Version:**
6.4.1

* **Browser:**
not applicable

* **Language:**
all

* **Loader/bundler:**
Webpack (didn't tested other)

**Current behavior:**
If target `environment.[tj]s` file is readonly, build fails when trying to copy corresponding file from `aurelia_project\environments`.

* **What is the expected behavior?**
As file created by aurelia on each build, readonly attribute should not fail entire build process.

* **What is the motivation / use case for changing the behavior?**
Team Foundation System with Server Repositories places readonly attribute on files that is not checked out. File `environment.[tj]s` is not exist on first build and copied with all attributes of source file, including readonly attribute as environment configuration files are rarely being edited and usually not checked out. Each subsequent build fails until either file or attribute removed. However, in this case source file copied again with all attributes. So it required to do manual cleanup before each build.

### PR DESCRIPTION
**Pull request by lorond**
closes #1031

### CODE REVIEW

**Comment by 3cp** [comment]
LGTM.

BTW, from your change, I noticed merge2 was not used by any file. Could you help to remove merge2 from `lib/dependencies.json` and `skeleton/cli-bundler/package.json`? Thx.

**Comment by lorond** [comment]
@3cp done

**Comment by 3cp** [comment]
@EisenbergEffect let’s merge this.

**Comment by EisenbergEffect** [comment]
@3cp Ready for a release or do you have other PRs still planned for this week?

**Comment by 3cp** [comment]
I will take some time to study the source map issue #1117

**Pull request merged**
