### PR TITLE
chore(#500): add npm scripts for au commands

### PR DESCRIPTION
**Pull request by sbolel**
### Summary of Changes

- implements [Feature Request] #500
- new projects are generated with a package.json that contains `au` commands in `scripts`

### CODE REVIEW

**Comment by AStoker** [comment]
Are there any downsides to this? I see the usefulness of this. On the other hand, would it cause confusion, because "building" could now happen with either `npm` or `au`, and if somebody has a custom build event (`au someBuild`), we don't want them to think that they can just use `npm someBuild`... What are your thoughts? @EisenbergEffect, what are your thoughts on that?

**Comment by sbolel** [comment]
Nice input @AStoker thanks!

- I agree it could lead to confusion. 
- Also, the two definitions could fall out of sync.

Frankly, I'm not entirely sure if I understand my own perceived issue 😅 

I enjoy using `au` as my primary cli because I can add custom commands with pretty help messages, no sweet. I'm concerned that if/when I don't use `npm` because...

I'm scared of the monster living under my bed.

**Comment by sbolel** [comment]
@AStoker, your https://github.com/aurelia/cli/issues/470#issuecomment-283146716 is great input for this as well.

**Comment by AStoker** [comment]
In regards to the monster under the bed, you could always just put the mattress directly on the floor, no hiding places then 😉 
In regards to the PR, I think it might be more up to @EisenbergEffect on which direction he wants to take. My [gut feeling](http://theawkwardyeti.com/comic/gut-instincts/) is that while yes, it provides some initial "lightening of the load", in the long run it might hurt more than help.

**Comment by sbolel** [comment]
> you could always just put the mattress directly on the floor, no hiding places then 

That's what I keep telling her, but she's all like "you never left college." `#yolo`

**Comment by EisenbergEffect** [comment]
If I can, I'd like to punt on this for now unless we hear a lot more community requests for this. I agree that it could become a source of confusion. I'm just not confident about doing it at this time.

**Comment by sbolel** [comment]
Agreed 👍

**Pull request closed without merging**
