### PR TITLE
feat: update command @PWKad #31

### PR DESCRIPTION
**Pull request by ahmedshuhel**

### CODE REVIEW

**Comment by ahmedshuhel** [comment]
@aurelia/cli-team I will rebase this again as soon as the core gets settled.

**Comment by PWKad** [comment]
This looks good to me as well.  I think the nuclear option can probably be removed but we can do so after confirming no one has issues with the standard update.

**Comment by ahmedshuhel** [comment]
@PWKad @zewa666 @joelcoxokc Rebased it. Please review.

**Comment by zewa666** [comment]
Ive noticed the Promise.all use instead Promise.join. Is that OK?

**Comment by ahmedshuhel** [comment]
@zewa666 I am not sure.

**Comment by ahmedshuhel** [comment]
https://github.com/petkaantonov/bluebird/blob/master/API.md#all---promise
@PWKad  Please confirm whether this is the behavior we want.

**Comment by PWKad** [comment]
Last I saw @zewa666 had mentioned to use Promise.join and @joelcoxokc was refactoring the `spawn-promise` module to use it.  I believe you guys had two different PRs and you refactored it to not use that and instead use Promise.all and something else.  I'm good with either method, I've not been testing it since you took this issue over.

**Comment by ahmedshuhel** [comment]
https://github.com/petkaantonov/bluebird/blob/master/API.md#promisejoinpromisethenablevalue-promises-function-handler---promise

Promise.join works for a fixed set of ops but performance wise superior. But, for us here as the number of modules to update are not fixed, `all` seems appropriate. I would request you to give it a run and see if it works way it should.

**Comment by joelcoxokc** [comment]
I think we moved to promise.join because we want the first to resolve
before the second.

**Comment by ahmedshuhel** [comment]
@joelcoxokc https://github.com/ahmedshuhel/cli/blob/update-command/src/lib/updater/index.js#L45

This is installing `arbitrary` number of jspm package in parallel. It's like running `jspm install` from multiple shell at the same time. One install does not depend on the  other. So `order` is not important here as much as I understand.

**Comment by PWKad** [comment]
@ahmedshuhel @joelcoxokc @zewa666 If this is working I'd like to merge it in before the next release as it takes a long time to explain how to update each repo to everyone :)

**Comment by ahmedshuhel** [comment]
@PWKad I believe it's working and we can get this In. Could you please give it a try and let us know the result?

**Pull request merged**
