### PR TITLE
update dotnet template to netcoreapp2.1, fix Index.cshtml

### LINKED ISSUE #979: ASP.NET Core template app does not run
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
TypeScript 3.0

* **Loader/bundler:**
Webpack

**Current behavior:**
Use `au new` to create a new Typescript/AspNetCore/Webpack project. Once it is complete and dependencies are installed, run project using `dotnet run`. The app loads with the word "Loading..." and nothing happens. In the console, a message `Loading failed for the <script> with source “http://localhost:5000/dist/vendor.bundle.js”.` is shown.
Looking at the dist folder, it indeed does not have that bundle. There is a app.bundle.js but no vendor.bundle.js.
When app is run using `au run` the app loads properly, and different output is shown in dist/ folder. Also building ASP.NET core app does not create/recreate the dist/ folder.
* **What is the expected behavior?**
To load and show Hello World.

* **What is the motivation / use case for changing the behavior?**

### PR DESCRIPTION
**Pull request by milkshakeuk**
Update the dotnet template but as well as updating the `Index.cshtml` which fixes #979

### CODE REVIEW

**Comment by milkshakeuk** [comment]
the reason this Travis Build is failing is because of a malicious dependency of `event-stream` called `flatmap-stream` [see here](https://github.com/dominictarr/event-stream/issues/115)

**Comment by huochunpeng** [comment]
You can rebase/merge latest master now.

**Comment by EisenbergEffect** [comment]
@milkshakeuk We've merged the event-stream fix into master. If you can rebase and ping me, I'll do a final review and we'll get this in. Thanks!

**Comment by milkshakeuk** [comment]
@EisenbergEffect the pull request has been rebased and is ready for review.

**Comment by huochunpeng** [comment]
Hoho, I know nothing about dotnet :-)

**Comment by huochunpeng** [comment]
I will have a look tomorrow, but my exp is probably limited at the cli side. @chrisckc could you have a look?

**Comment by huochunpeng** [comment]
Most code are dotnet templates that I am not familiar. But the few lines of cli code look good to me.

**Comment by EisenbergEffect** [comment]
It looks fine as well, from what I can tell, but I'm not the expert. Let me see if I can get a core team .NET user to give this a test as well

**Comment by Alexander-Taran** [comment]
@milkshakeuk could you explain 
`.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);`
and
`UseHsts()`
lines..
They seem opinionated
And if so - should be commented.
As in "as better developers we want to enforce https early.."
That is if I'm getting this line right.

And compatibility I don't get.
I've lost track of .net core

**Comment by milkshakeuk** [comment]
@Alexander-Taran the changes I have added are taken pretty much verbatim from the result of `dotnet new mvc` .

None of what I have added is opinionated on my part but if your interested in the reasons behind the `SetCompatibilityVersion` [see here](https://blogs.msdn.microsoft.com/webdev/2018/02/27/introducing-compatibility-version-in-mvc/).

There is also some information in the [official docs](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio) relating to `UseHsts`.

**Comment by EisenbergEffect** [comment]
Thanks for working on this @milkshakeuk ! Merging it in for the next release.

**Pull request merged**
