### PR TITLE
doc(readme): add instructions to run CLI locally

### PR DESCRIPTION
**Pull request by JeroenVinke**
closes https://github.com/aurelia/cli/issues/451

### CODE REVIEW

**Comment by s-hoff** [comment]
For testing with the TS setup one would need the `typescript` package.
esprima also no longer needs to be installed this way as it is already in the devDependencies.
I'm a little curious about gulp: Wouldn't it be better to have the same version in the cli's devDependencies as in the projects set up by it?

**Comment by JeroenVinke** [comment]
@s-hoff thanks for looking it over! I have removed esprima and added typescript. Regarding using gulp 4.0 as the devDependency, it's a good idea, but considering all other libraries are on gulp 3.9.1 I think we should wait and move all libraries over to gulp 4 when that's released.

 I tried using gulp 4 and ran into this beauty:

```
PS C:\Development\cli> gulp prepare-release
[10:06:36] Using gulpfile C:\Development\cli\gulpfile.js
[10:06:36] Starting 'prepare-release'...
[10:06:36] 'prepare-release' errored after 4.11 ms
[10:06:36] TypeError: gulp.hasTask is not a function
    at C:\Development\cli\node_modules\run-sequence\index.js:19:22
    at Array.forEach (native)
    at verifyTaskSets (C:\Development\cli\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\Development\cli\node_modules\run-sequence\index.js:92:2)
    at C:\Development\cli\build\tasks\prepare-release.js:25:10
    at taskWrapper (C:\Development\cli\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (C:\Development\cli\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
```

Indicating that run-sequence does not work with gulp 4 (yet)

**Comment by s-hoff** [comment]
Sounds good to me.

**Comment by ghidello** [comment]
Accordingly to [this](https://github.com/OverZealous/run-sequence#please-note) comment I don't think that the run-sequence package will be updated to gulp 4. We'll have to rewrite the pre-release task using the new gulp.series() api when we'll prepare for the jump to gulp 4.

**Pull request merged**
