### PR TITLE
fixed(docker): fixed docker tests for second configuration

### PR DESCRIPTION
**Pull request by shahabganji**
Changed some of the CircleCi tests, and moved the second configuration to travis.

@3cp please take a look .

### CODE REVIEW

**Comment by 3cp** [comment]
The travis config didn't use `npm link`, how does it use local aurelia-cli to generate skeleton?

**Comment by 3cp** [comment]
The circleci issue is fixed in #1167, the root cause is protractor default browser window size (in docker or vm) is too small.

**Comment by shahabganji** [comment]
> The travis config didn't use `npm link`, how does it use local aurelia-cli to generate skeleton?

[here](https://github.com/aurelia/cli/pull/1168/commits/94659968118be2730810dfc90dbded23d0fb4a38#diff-354f30a63fb0907d4ad57269548329e3R34) `npm link aurelia-cli` is used.




> The circleci issue is fixed in #1167, the root cause is protractor default browser window size (in docker or vm) is too small.

That is kind of weird, is that differs from docker in Travis and docker in CircleCI?

**Comment by 3cp** [comment]
> That is kind of weird, is that differs from docker in Travis and docker in CircleCI?

No idea :-(

**Comment by 3cp** [comment]
I see. So your `au new` is before link, that means the skeleton is generated using globally installed aurelia-cli from npm?

**Pull request closed without merging**
