### PR TITLE
fix(vm): fixes multiple inject decorators to single

### PR DESCRIPTION
**Pull request by zewa666**
the template will now use one inject decorator and apply multiple targets as attributes

### CODE REVIEW

**Comment by PWKad** [comment]
:+1: From me, assuming syntactically everything is correct this looks fine.

**Comment by joelcoxokc** [comment]
This has been created... Checkout @EisenbergEffect and my conversation... and the docs I have been posting about the commander API. I actually Like your implementation better than mine... We should probably consider using yours in `aurelia-command`. However. Rob suggested that we try to use the DI. What do you think @zewa666

**Comment by EisenbergEffect** [comment]
FYI That generated code is still not correct. `Element` is not in aurelia-framework. That is a browser global. Also, if you use the `@inject` decorator, you will need to import that from aurelia-framework.

**Comment by zewa666** [comment]
Damn need to make better reviews before commiting stuff. Regarding imports, I could create an exception for Element, but other then that how would we know where to import from? So the idea was to always use the framework and let the user fix it afterwards.

**Comment by EisenbergEffect** [comment]
Hmmm. There might be lots of exceptions.

**Comment by zewa666** [comment]
@EisenbergEffect the `inject` object was already imported in case of injection used, dunno if you saw something else. Have added now the exception for the global Element object.

As said not sure whether we have a chance to automatically know where things come from, especially also if the user injects local files. So I guess we'll have to have our users fix the import paths.

**Comment by ahmedshuhel** [comment]
:+1: from me too.

**Pull request merged**
