### PR TITLE
feat(cli build): add build targets

### PR DESCRIPTION
**Pull request by jwx**
Configure build target folders in aurelia.json that builds complete distribution folders.

Changes:
- complete build is made into target root folder based on env (default: build/dev)
- source files in src are never touched
- source file environment.js/ts is never copied into src
- files index.html and favicon.ico should be in root directory
- build.targets.<env>.root key is used for .Net Core and similar with specific directory requirements
aurelia.json:
- build.targets changed from array to object with env names (dev, stage, prod) as keys
- build.targets.[0].baseDir removed in favour of build.targets.<env>.root

Closes aurelia/cli#200, aurelia/cli#442, aurelia/cli#563 and aurelia/cli#627.

### CODE REVIEW

**Comment by AshleyGrant** [comment]
@JeroenVinke would you mind giving this PR a look? I've got a client this feature would really be useful for.

**Comment by JeroenVinke** [comment]
@AshleyGrant I've had a look, and I like the idea of this. There are actually two use cases here that we need to cover:

- output to environment-specific build folders (dist/dev, dist/prod)
- electron, cordova etc

I would like to wait a little while before we merge this PR, so we don't end up needing to introduce a breaking change when we add support for electron/cordova

**Comment by alecb67** [comment]
@JeroenVinke Any idea how long until this will be merged?

**Comment by JeroenVinke** [comment]
That's not certain yet. It depends on a lot of other factors. My guess is that is will be a while

**Comment by alecb67** [comment]
No problem, thanks for the rough estimate anyway!

**Comment by jwx** [comment]
I'm working on a new PR that will cover the listed needs. Once it's done, it will probably replace this. I'll link to the new PR once it's in. @alecb67 @AshleyGrant

**Comment by jwx** [comment]
The new PR is in: https://github.com/aurelia/cli/pull/765. @alecb67 @AshleyGrant

**Comment by EisenbergEffect** [comment]
Closing in favor of #765.

**Pull request closed without merging**
