### PR TITLE
chore(all): upgrade user app dependencies

### PR DESCRIPTION
**Pull request by 3cp**
There are few important major version upgrades, like systemjs, jest, babel-plugin-istanbul, gulp-typescript, karam-jasmine. Pending full release-check.

### CODE REVIEW

**Comment by 3cp** [comment]
@shahabganji 👍 your docker test covered quite a few skeletons, saved lots of time on the debug.

Maybe we should cover all the 72 skeletons that our release-check overed, if circleci didn't complain abuse 😄

**Comment by 3cp** [comment]
jest-cli changed api totally, without clear doc...

**Comment by shahabganji** [comment]
@3cp , I see some of the tests have failed, is it due to ai changes of jest? 

I think we could have 72 tests, at least in theory, in prcatice we should see how many concurrent tasks we could run on CircleCI. I don't know excatly about that.

**Comment by 3cp** [comment]
Ok, the jest runCLI is moved from jest-cli to `@jest/core`.

I need to do full local release-check now.

**Comment by 3cp** [comment]
release-check passed on both win10 and macos.

**Pull request merged**
