### PR TITLE
feat(bundler): add target flag

### PR DESCRIPTION
**Pull request by johan-v-r**
Related to #724

### CODE REVIEW

**Comment by JeroenVinke** [comment]
Thanks @johan-v-r. We are planning to add build targets for electron etc to the cli so i'll have to wait and see if this aligns with those plans but on first sight this looks great.

**Comment by johan-v-r** [comment]
Okay no problem thanks for the feedback @JeroenVinke, I have a similar custom work-around I will post on the referenced issue.

**Comment by EisenbergEffect** [comment]
@JeroenVinke How does this relate to the larger build target work?

**Comment by JeroenVinke** [comment]
@johan-v-r thank you for working on this PR. I plan on merging https://github.com/aurelia/cli/pull/765 which should cover this. Let me know if that ends up not being the case

**Pull request closed without merging**
