### PR TITLE
fix(importer): prevent duplicate dist

### PR DESCRIPTION
**Pull request by gishmel**
closes https://github.com/aurelia/cli/issues/671

### CODE REVIEW

**Comment by JeroenVinke** [comment]
@gishmel could you rename this commit so that it follows our [guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#-git-commit-guidelines)? That will cause it to show up in our release notes

**Comment by gishmel** [comment]
Hows that?

**Comment by JeroenVinke** [comment]
Could you give https://stackoverflow.com/a/20853093 a shot? The goal is to have an updated commit message in git, which is different from the title of the pull request in github. The commands in the stackoverflow post needs to be done on the branch that you created the PR for. When that is done you should see the updated commit message in https://github.com/aurelia/cli/pull/674/commits. Let me know if you run into any issues

**Comment by gishmel** [comment]
Yep sorry for the confusion done. Was thinking about amending my commit but didn't realize that's what you wanted. Hopefully its all good now?

**Comment by JeroenVinke** [comment]
Much better! It might be a bit too long. If you could shorten it, then it's perfect. Something like `fix(importer): prevent duplicate dist` should be good

**Comment by gishmel** [comment]
Okay I just wanted to illustrate it would cause any duplicate paths between package.path and resources path to be removed but yeah I guess its fine as it will still do just that.

**Comment by JeroenVinke** [comment]
Does this also work for a deeper folder structure? E.g. output/dist/test.css

**Comment by gishmel** [comment]
No I did not change the underlying how it got access to the folder structure as its a fairly simplistic regular expression using the glob package. I can modify if need be just I don't believe that is at all addressed in the current implementation of the resource-inclusion package; at least from my reading and understanding of the code.

**Pull request merged**
