### PR TITLE
Add TravisCI support

### PR DESCRIPTION
**Pull request by mbroadst**
* add a .travis.yml for automatically running continuous integration for the cli repo
* add TravisCI badge to the README.md

### CODE REVIEW

**Comment by mbroadst** [comment]
arg, sorry about the whitespace changes.. I have sublime set up automatically trim all that whitespace. Let me know if you'd prefer I resubmit the PR without that

**Comment by EisenbergEffect** [comment]
@AshleyGrant Can you review this and see how it aligns with the work you are doing for automated testing?

**Comment by mbroadst** [comment]
@EisenbergEffect IMHO for the framework as a whole you'll be able to (and certainly want to) test far more configurations than Travis alone can provide you. However, for something like the CLI I think Travis is a decent solution. 

Additionally, Travis could be enabled for all builds to provide a form of redundant testing, but that also doubles the workload of your test engineers :smile:

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Can you review this. It's been sitting here a while and would be great to get set up if possible.

**Comment by EisenbergEffect** [comment]
@mbroadst Thanks for putting this together. We've decided to change strategy a bit around the cli so I'm going to close this for now.

**Pull request closed without merging**
