### PR TITLE
Remove readonly attribute on destination environment file

### PR DESCRIPTION
**Pull request by lorond**
Issue: https://github.com/aurelia/cli/issues/1031
Based on: https://github.com/gulpjs/gulp/issues/1057#issuecomment-99211021

### CODE REVIEW

**Comment by lorond** [comment]
need to revise, found bug

**Comment by avrahamcool** [comment]
what bug did you find?

**Comment by huochunpeng** [comment]
If your problem is testing...

Currently tests only runs on nodejs v8, not v10.

Check `.travis.yml` for more details.

**Comment by lorond** [comment]
> keep in mind you need to manually delete the destination file that was created before your fix (because it already have the readonly flag).

yep, that is why I simply want to remove readonly flag on destination file.

**Pull request closed without merging**
