### PR TITLE
WIP fix(bundler): support nodejs subfolder package.json

### PR DESCRIPTION
**Pull request by huochunpeng**
This fix implemented full algorithm described in https://nodejs.org/dist/latest-v8.x/docs/api/modules.html, after "high-level algorithm in pseudocode of what require.resolve() does".
Came from https://discourse.aurelia.io/t/aurelia-cli-bundler-1-0-0-beta-firebase/1759

### CODE REVIEW

**Comment by huochunpeng** [comment]
I think circleci docker images are all linux environment. Is there a way to setup circleci to test a nodejs version on windows?

**Comment by huochunpeng** [comment]
Holding for few mins, doing testing on windows box.

**Comment by huochunpeng** [comment]
@EisenbergEffect how did you merged? I got "WIP" in the title. I think github got a timing bug.

**Comment by EisenbergEffect** [comment]
Sorry! I saw your message in discourse and proceeded with the merge. Should I revert or wait for a follow-up PR with any Windows fixes?

**Pull request merged**
