### PR TITLE
fix(package-analyzing): allow deeper levels for source root

### PR DESCRIPTION
**Pull request by alpox**
As i announced, here is the PR i provided earlier.

Before, the package-analyzer looked for the node_modules folder in only exactly one path step back
to the source files.
I changed this behaviour to use a node-like lookup which looks for the node_modules folder in
the following manner:
./node_modules, ../node_modules, ../../node_modules, etc.

And this allows to put the root of the source (project.paths.root) somewhere deeper in a file-structure.

See Issue https://github.com/aurelia/cli/issues/278

This is a new PR for: https://github.com/aurelia/cli/pull/295

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@alpox Apologies. Somehow I missed this PR or got it confused with the earlier one that you said not to take. I'm interested in getting this incorporated, however it's now conflicting with other changes made in the package-analyzer. Can you look into rebasing and resolving any conflicts?

**Comment by alpox** [comment]
@EisenbergEffect No problem!

I rebased and resolved all the conflicts and also applied a little change to build/bundle.js to prevent the previous possible matter, that dependencies could load in a wrong order. I had to apply this change to make my changes in package-analyzer.js work, since there is new asynchronous computation for the node_modules folder lookup.

I hope i did everything right with the rebasing :smile:
Best, alpox

**Comment by EisenbergEffect** [comment]
@alpox The rebase isn't quite right ;) Sorry to do this with you but I think it's better if you submit a new PR based on master. This one is impossible to review as it. Sorry to do that to you? Can you create a brand new PR from master?

**Comment by alpox** [comment]
@EisenbergEffect My bad. Sorry for that :-) I'll be happy to give it another try with a new PR. You're right, the changes are not visible anymore. :-(

**Comment by EisenbergEffect** [comment]
No worries. These things happen sometimes. If you can submit a new PR based on master, we can take it from there. Thanks!

**Comment by alpox** [comment]
@EisenbergEffect already there. Thank you for your time!

**Pull request closed without merging**
