### PR TITLE
fix(bundler): fix sourceMap source file path and sourceRoot

### PR DESCRIPTION
**Pull request by huochunpeng**
The source path should be relative path, not the absolute disk file path. sourceRoot is removed in final bundle source map.

### CODE REVIEW

**Comment by huochunpeng** [comment]
@Alexander-Taran can you try whether this one can replace #1078?

**Comment by huochunpeng** [comment]
Tested the generated source map on both windows and mac.

**Comment by Alexander-Taran** [comment]
@huochunpeng works for me and my weird setup.

**Comment by huochunpeng** [comment]
@EisenbergEffect safe to merge. This cleans up sourceMap source map in browser display.

**Pull request merged**
