### PR TITLE
Decorated command

### PR DESCRIPTION
**Pull request by ahmedshuhel**
This PR includes the followings:
- Fixes the problems of #90 and #98 .
- `generate`, `new`, `bundle`, `init` commands are converted  to new decorator based command interface
- Includes the dynamic command loading for built in commands #88

@PWKad @zewa666  @joelcoxokc please review this.

### CODE REVIEW

**Comment by zewa666** [comment]
looks good for me :+1:

**Comment by PWKad** [comment]
Assuming everything runs correctly, looks good to me :+1:

**Comment by ahmedshuhel** [comment]
Merging this as we have necessary votes.

@PWKad could you please try it on a mac machine? https://github.com/aurelia/cli/issues/59 is a problem we are having for a long time. As I don't have a mac I can't re produce this.

**Comment by joelcoxokc** [comment]
Are we not using the decorators from aurelia-command?

**Comment by ahmedshuhel** [comment]
@joelcoxokc I tried to fix the problem with `aurelia-command` but could not. It was hard for me to get the hold of the `context`. Then I  implemented it with commanderjs keeping the interface same.

**Pull request merged**
