### PR TITLE
refactor(custom typings): Change folder name

### LINKED ISSUE #1061: (Suggestion) Rename custom_typings to types
**I'm submitting a change request**

* **Library Version:**
cli latest

* **Operating System:**
N/A

* **Node Version:**
N/A

* **NPM Version:**
N/A

* **Browser:**
all 

* **Language:**
TS

* **Loader/bundler:**
Webpack

**Current behavior:**
Additional typing are placed in a folder called `custom_typings`

* **What is the requested behavior?**
Place typings in a folder called `types`

* **What is the motivation / use case for changing the behavior?**
If you use vscode to auto generate a typing it will place it in a folder called `types` and automatically updated the tsconfig for you. Not sure if this is a standard for placing custom typings but it would be nice to match vscode's preferred location.

Please let me know your thoughts, if you agree I can implement this small change.

### PR DESCRIPTION
**Pull request by michaelw85**
Change folder from custom_typings to types matching folder name used by
vscode when auto generating d.ts files.

Closes #1061

### CODE REVIEW

**Comment by michaelw85** [comment]
Update PR based on latest code in master.
@huochunpeng @EisenbergEffect Could this PR/request be reviewed?

**Comment by EisenbergEffect** [comment]
Deferring to @huochunpeng

**Comment by EisenbergEffect** [comment]
This does make good sense to me. Just want to get the final approval from @huochunpeng or @JeroenVinke

**Comment by huochunpeng** [comment]
Not my expertise to approve anything related to TypeScript. But the code changes looks correct.

**Pull request merged**
