### PR TITLE
fix(package-analyzer): temporarily work around "module" field in package.json

### LINKED ISSUE #960: CLI auto-tracing es2015/commonjs paths problem
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **Browser:**
Chrome 17

* **Language:**
TypeScript 3.1

* **Loader/bundler:**
RequireJS

**Current behavior:**

* **What is the expected behavior?**
We have to run our aurelia project on really old browser - Chrome 15-17. 
On pre 1.0 version everything worked fine

Now we get error "Use of const in strict mode".
image

How to force compile _const/let_ to _var_ in cli?
How does aurelia cli auto-tracing get its dependencies? Some are from commonjs and some from es2015 folder although in package.json paths are the same
```
define('aurelia-binding',['aurelia-binding/dist/es2015/aurelia-binding'],function(m){return m;});
define('aurelia-bootstrapper',['aurelia-bootstrapper/dist/commonjs/aurelia-bootstrapper'],function(m){return m;});
define('aurelia-dependency-injection',['aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection'],function(m){return m;});
define('aurelia-framework',['aurelia-framework/dist/commonjs/aurelia-framework'],function(m){return m;});
define('aurelia-loader',['aurelia-loader/dist/commonjs/aurelia-loader'],function(m){return m;});
define('aurelia-loader-default',['aurelia-loader-default/dist/commonjs/aurelia-loader-default'],function(m){return m;});
define('aurelia-logging',['aurelia-logging/dist/commonjs/aurelia-logging'],function(m){return m;});
define('aurelia-metadata',['aurelia-metadata/dist/commonjs/aurelia-metadata'],function(m){return m;});
define('aurelia-pal',['aurelia-pal/dist/commonjs/aurelia-pal'],function(m){return m;});
define('aurelia-pal-browser',['aurelia-pal-browser/dist/commonjs/aurelia-pal-browser'],function(m){return m;});
define('aurelia-path',['aurelia-path/dist/commonjs/aurelia-path'],function(m){return m;});
define('aurelia-polyfills',['aurelia-polyfills/dist/commonjs/aurelia-polyfills'],function(m){return m;});
define('aurelia-task-queue',['aurelia-task-queue/dist/commonjs/aurelia-task-queue'],function(m){return m;});
define('aurelia-templating',['aurelia-templating/dist/es2015/aurelia-templating'],function(m){return m;});

```

* **What is the motivation / use case for changing the behavior?**
Support for old Webkit

### PR DESCRIPTION
**Pull request by bigopon**
Per @huochunpeng 

cc @JeroenVinke @EisenbergEffect 

resolves #960

### CODE REVIEW

**Comment by huochunpeng** [comment]
Thx!

**Comment by huochunpeng** [comment]
This temporarily ignores module field for all core aurelia modules (plus some 3rd party plugins starting with aurelia-).

For long term, we will revert this patch, then use dist/amd for all core aurelia modules (if the folder exists).

**Comment by huochunpeng** [comment]
The more I think about it, this "temporary" patch may be good enough to restore aurelia’s compatibility on old browsers.

My proposed long term fix involves more code change without extra benefit, in other word, unnecessary.

**Comment by EisenbergEffect** [comment]
Ok, so I probably need to get this merged and released ASAP. Can someone confirm?

**Comment by huochunpeng** [comment]
Yes pls.

**Pull request merged**
