### PR TITLE
fix(webpack): avoid unnecessary breaking change on argument

### PR DESCRIPTION
**Pull request by 3cp**
With this fix, `au run --analyze` `au run --hmr` will continue to work.

### CODE REVIEW

**Comment by 3cp** [comment]
@Sayan751 pls review this fix.

**Comment by 3cp** [comment]
@EisenbergEffect I cannot use github tool to request review from @Sayan751. Is there some member setup you need to do?

**Comment by EisenbergEffect** [comment]
For some reason you can't just add anyone as a reviewer. I don't know why GH has that restriction. We can always ping @Sayan751 manually and ask him to take a look.

**Comment by Sayan751** [comment]
@3cp Sorry for the late reply. The changes looks good to me. I have seen this issue https://github.com/aurelia/cli/issues/1147 as well. Let's continue the discussion there.

**Pull request merged**
