### PR TITLE
doc: document auto-tracing bundler

### PR DESCRIPTION
**Pull request by huochunpeng**
Make clear webpack and built-in bundler are two options.
Promote prepend over shim.
Slice the long bundler doc into few chapters.
Add cookbook of common usage like jquery and bootstrap.
To be merged after #862.

### CODE REVIEW

**Comment by huochunpeng** [comment]
@EisenbergEffect the companion site-generator config for review:
```json
{
  "name": "The Aurelia CLI",
  "description": "Learn how to create, build, bundle and test your apps using all your favorite tools, facilitated by the Aurelia CLI.",
  "dest": "docs/cli",
  "items": [
    {
      "name": "Basics",
      "src": "../cli/doc/article/en-US/basics.md",
      "dest": "docs/cli/basics"
    },
    {
      "name": "Tasks",
      "src": "../cli/doc/article/en-US/gulp-tasks.md",
      "dest": "docs/cli/tasks"
    },
    {
      "name": "Webpack (default)",
      "src": "../cli/doc/article/en-US/webpack.md",
      "dest": "docs/cli/webpack"
    },
    {
      "name": "Built-in Bundler (alternative)",
      "description": "CLI Built-in Bundler is an alternative bundler to webpack. It provides similar capability but with much simpler configuration. If you have no experience on Webpack, we recommend the built-in bundler.",
      "dest": "docs/cli/cli-bundler",
      "items": [
        {
          "name": "Basics",
          "src": "../cli/doc/article/en-US/cli-bundler/basics.md",
          "dest": "docs/cli/cli-bundler/basics"
        },
        {
          "name": "Dependency Management",
          "src": "../cli/doc/article/en-US/cli-bundler/dependency-management.md",
          "dest": "docs/cli/cli-bundler/dependency-management"
        },
        {
          "name": "Advanced Features",
          "src": "../cli/doc/article/en-US/cli-bundler/advanced.md",
          "dest": "docs/cli/cli-bundler/advanced"
        },
        {
          "name": "Cookbook",
          "src": "../cli/doc/article/en-US/cli-bundler/cook-book.md",
          "dest": "docs/cli/cli-bundler/cook-book"
        }
      ]
    },
    {
      "name": "Migrating",
      "src": "../cli/doc/article/en-US/migrating.md",
      "dest": "docs/cli/migrating"
    },
    {
      "name": "Updating",
      "src": "../cli/doc/article/en-US/updating.md",
      "dest": "docs/cli/updating"
    },
    {
      "name": "Recipes & Known Issues",
      "src": "../cli/doc/article/en-US/recipes.md",
      "dest": "docs/cli/recipes"
    }
  ]
}
```

**Comment by EisenbergEffect** [comment]
Excellent! How close is #862 ?

**Comment by huochunpeng** [comment]
I am very content about the state of #862. Just read all the commit messages, feature-wise it's comparable to webpack.

**Comment by huochunpeng** [comment]
@EisenbergEffect @JeroenVinke 
Before merging auto-tracing, suggest to release another v0.35 after review and merging #908 #913.

**Comment by EisenbergEffect** [comment]
That sounds good to me. @JeroenVinke What do you think?

**Comment by bigopon** [comment]
Wow read the `.md` files. A lot of effort. Very nice @huochunpeng 👍

**Comment by zewa666** [comment]
This is massive. Love to see you got all the weird cases from my app documented :) awesome work

**Comment by JeroenVinke** [comment]
Great work! I’ll take a look at both pr’s and prepare a release

**Pull request merged**
