### PR TITLE
feat(tests): test setup for the CLI

### PR DESCRIPTION
**Pull request by zewa666**
adds a test setup with jasmine-node and an example test

relates to issue #14

### CODE REVIEW

**Comment by zewa666** [comment]
Sry but it seems I can't assign tickets via ZenHub in this repo, guess it's related to permissions. Anyways this shows how to create a sample unit test with jasmine-node. In order to execute them please run `npm install -g jasmine-node@2.0.0` and then from the commandline inside the cli rootfolder `jasmine-node test` where test is the name of the folder containing the tests.

As for integration testing i have to look into https://github.com/lehmannro/assert.sh, this might be tricky for windows users like me :)

**Comment by EisenbergEffect** [comment]
@zewa666 I've added you to the CLI team. You should be good to go from now on.

**Comment by joelcoxokc** [comment]
@PWKad mentioned that we should creating branches off of the cli master. This is not a big issue at the moment, because all of my previous PR's were form my local repo as well. However, after this PR is merged, lets start creating feature branches off master.

**Comment by joelcoxokc** [comment]
I approve of this PR. 
I would like to start writing tests as well so I will go ahead and merge.

**Pull request merged**
