### PR TITLE
lint and changelog

### PR DESCRIPTION
**Pull request by JeroenVinke**
https://github.com/aurelia/cli/issues/516

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Looks like some conflicts now.

**Comment by JeroenVinke** [comment]
Should be good now

**Comment by JeroenVinke** [comment]
Also added a circle.yml file which runs the linter and runs the unit tests that are going to be introduced by https://github.com/aurelia/cli/pull/481.

**Comment by EisenbergEffect** [comment]
@JeroenVinke Please ping me when #481 is ready and I'll get that and this all merged in.

**Comment by JeroenVinke** [comment]
@EisenbergEffect good to go. Can you also verify that circleCI is enabled on this repo?

**Comment by EisenbergEffect** [comment]
CI is not enabled :)

**Pull request merged**
